export const sample_market_data = [
    {
        id: '1',
        location:'Mainland',
        market: 'Yaba',
        shop: 'Iya Tayo',
        name: 'Tomatoes',
        favourite: false,
        stars: 4,
        imageUrl: 'grocery-1.jpg',
        tags: ['grocery', 'Tomtoes', 'Yaba'],
        price: 500,
        stock: 1000,
        otherInformation: "0.5kg at 500, 1000kg in stock"
    },
    {
        id: '2',
        location:'Mainland',
        market: 'Mile 12',
        shop: 'Iya Semi',
        name: 'Tomatoes',
        favourite: true,
        stars: 4.5,
        imageUrl: 'grocery-2.jpg',
        tags: ['grocery', 'Tomtoes', 'Mile 12'],
        price: 550,
        stock: 2000,
        otherInformation: "0.5kg at 500, 2000kg in stock"
    },
    {
        id: '3',
        location:'Mainland',
        market: 'Oyingbo',
        shop: 'Iya Ola',
        name: 'Pepper',
        favourite: false,
        stars: 3.5,
        imageUrl: 'grocery-3.jpg',
        tags: ['grocery', 'Pepper', 'Mile 12'],
        price: 250,
        stock: 2000,
        otherInformation: "0.5kg at 245, 2000kg in stock"
    },
    {
        id: '4',
        location:'Island',
        market: 'Ajah',
        shop: 'Mma Damian',
        name: 'Onions',
        favourite: false,
        stars: 4.5,
        imageUrl: 'grocery-4.jpg',
        tags: ['grocery', 'Onions', 'Ajah'],
        price: 100,
        stock: 2500,
        otherInformation: "0.5kg at 100, 2500kg in stock"
    },
    {
        id: '5',
        location:'Island',
        market: 'Ajah',
        shop: 'David Short',
        name: 'Garri',
        favourite: false,
        stars: 4,
        imageUrl: 'grocery-5.jpg',
        tags: ['grocery', 'Garri', 'Ajah'],
        price: 5000,
        stock: 500,
        otherInformation: "2kg at 5000, 10 50kg bags in stock"
    },
    {
        id: '6',
        location:'Island',
        market: 'Epetedo',
        shop: 'Mrs Oni',
        name: 'Garri',
        favourite: true,
        stars: 3.5,
        imageUrl: 'grocery-6.jpg',
        tags: ['grocery', 'Garri', 'Epe'],
        price: 15000,
        stock: 100,
        otherInformation: "5kg at 15000, 100 5kg bags in stock"
    },
]